import {generateRows,generateRow} from './sheetUtils'
export default [
    [
        {value:'增值税减免税申报明细表',readOnly:true,colSpan:7}
    ],
    [
        {value:'一、减税项目',readOnly:true,colSpan:7}
    ],
    [
        {value:'减税性质代码及名称',readOnly:true,rowSpan:2},
        {value:'栏次',readOnly:true,rowSpan:2},
        {value:'期初余额',readOnly:true},
        {value:'本期发生额',readOnly:true},
        {value:'本期应抵减税额',readOnly:true},
        {value:'本期实际抵减税额',readOnly:true},
        {value:'期末余额',readOnly:true}
    ],
    [
        {value:'1',readOnly:true},
        {value:'2',readOnly:true},
        {value:'3=1+2',readOnly:true},
        {value:'4≤3',readOnly:true},
        {value:'5=3-4',readOnly:true}
    ],
    [
        ...generateRow('A',['合计',1],5)
    ],
    ...generateRows([[],[],[],[],[],[]],7,'B'),
    [
        {value:'二、免税项目',readOnly:true,colSpan:7}
    ],
    [
        {value:'免税性质代码及名称',readOnly:true,rowSpan:2},
        {value:'栏次',readOnly:true,rowSpan:2},
        {value:'免征增值税项目销售额',readOnly:true},
        {value:'免税销售额扣除项目本期实际扣除金额',readOnly:true},
        {value:'扣除后免税销售额',readOnly:true},
        {value:'免税销售额对应的进项税额',readOnly:true},
        {value:'免税额',readOnly:true}
    ],
    [
        {value:'1',readOnly:true},
        {value:'2',readOnly:true},
        {value:'3=1-2',readOnly:true},
        {value:'4',readOnly:true},
        {value:'5',readOnly:true}
    ],
    [
        ...generateRow('A',['合计',1],5)
    ],
    ...generateRows([[],[],[],[],[],[]],7,'B')
];